light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO33
     
i2c:
  sda: 16
  scl: 4
  frequency: 100kHz
     
 
mcp23017:
  - id: 'mcp23017_inputs_1'
    address: 0x20
    open_drain_interrupt: true
     
  - id: 'mcp23017_inputs_2'
    address: 0x21
    open_drain_interrupt: true
 
  - id: 'mcp23017_inputs_3'
    address: 0x22
    open_drain_interrupt: true
 
  - id: 'mcp23017_inputs_4'
    address: 0x23
    open_drain_interrupt: true
     
  - id: 'mcp23017_outputs_1'
    address: 0x24
     
  - id: 'mcp23017_outputs_2'
    address: 0x25
     
  - id: 'mcp23017_outputs_3'
    address: 0x26
     
  - id: 'mcp23017_outputs_4'
    address: 0x27
 
# Individual inputs
binary_sensor:
  - platform: gpio
    name: "Input #1"
    pin:
      mcp23xxx: mcp23017_inputs_3
      number: 0
      mode:
        input: true
      interrupt: CHANGE
     
# Individual outputs
switch:
  - platform: gpio
    name: "Output #1"
    pin:
      mcp23xxx: mcp23017_outputs_3
      number: 0
      mode:
        output: true